name: Update data.json

on:
  push:
    branches:
      - update-requests

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout update-requests
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Switch to main and update file
        run: |
          git fetch origin main
          git checkout main
          cp data.json data.json
          git add data.json
          git commit -m "Update data.json from admin dashboard" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/elusiee/elusiee.github.io.git main
